import:
  - tabs.yaml
  - playerctl.yaml

options:
  move_threshold: 0.15

gestures:
  - name: Previous workspace
    sequence:
      - fingers: 4
        action: move left
    repeatable: true
    command: hyprctl dispatch workspace r-1
    matching_windows:
      - firefox-developer-edition

  - name: Next workspace
    sequence:
      - fingers: 4
        action: move right
    repeatable: true
    command: hyprctl dispatch workspace r+1
    matching_windows:
      - firefox-developer-edition
