import:
  - tabs.yaml
  - playerctl.yaml

options:
  move_threshold: 0.15

gestures:
  - name: Previous workspace
    sequence:
      - fingers: 3
        action: move left
    repeatable: true
    command: hyprctl dispatch workspace r-2

  - name: Next workspace
    sequence:
      - fingers: 3
        action: move right
    repeatable: true
    command: hyprctl dispatch workspace r+0