import:
  - browser.yaml
  - playerctl.yaml
  - kitty.yaml
  - jetbrains.yaml
  - vim.yaml

options:
  move_threshold: 0.15

  edge:
    threshold: 0.05
    sensitivity: 0.5

gestures:
  - name: Previous workspace
    sequence:
      - fingers: 4
        action: move left
    repeat_mode: slide
    command: hyprctl dispatch workspace r-1

  - name: Previous workspace
    sequence:
      - fingers: 1
        action: move left
        edge: bottom
    repeat_mode: slide
    command: hyprctl dispatch workspace r-1

  - name: Next workspace
    sequence:
      - fingers: 4
        action: move right
    repeat_mode: slide
    command: hyprctl dispatch workspace r+1

  - name: Next workspace
    sequence:
      - fingers: 1
        action: move right
        edge: bottom
    repeat_mode: slide
    command: hyprctl dispatch workspace r+1

  - name: Toggle special:terminal workspace
    sequence:
      - fingers: 1
        action: move down
        edge: top
    repeat_mode: tap
    command: hyprctl dispatch togglespecialworkspace terminal

  - name: Kill active window
    sequence:
      - fingers: 4
        action: move down
    command: hyprctl dispatch killactive

  - name: Brightness up
    sequence:
      - fingers: 1
        action: move up
        edge: right
    repeat_mode: slide
    command: brightnessctl set 10%+

  - name: Brightness down
    sequence:
      - fingers: 1
        action: move down
        edge: right
    repeat_mode: slide
    command: brightnessctl set 10%-
